# Generated by Django 5.0.6 on 2024-06-18 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printhub_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shoprate',
            table='shop_rate_new_name',
        ),
    ]
