# Generated by Django 5.0.6 on 2024-06-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printhub_app', '0004_testfile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testfile',
            table='test_file',
        ),
    ]
