# Generated by Django 5.0.6 on 2024-06-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printhub_app', '0005_alter_testfile_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestFile',
        ),
    ]
