# Generated by Django 5.0.6 on 2024-06-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printhub_app', '0006_delete_testfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='custom_page_size',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='file_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='page_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='paper_color',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
