# Generated by Django 5.0.6 on 2024-06-28 06:03

import printhub_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printhub_app', '0007_userfile_custom_page_size_userfile_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='actual_page_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(upload_to=printhub_app.models.UploadToUserFolder()),
        ),
    ]
