# Generated by Django 5.0.6 on 2024-06-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printhub_app', '0008_userfile_actual_page_size_alter_userfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='actual_page_size',
        ),
        migrations.AddField(
            model_name='userfolder',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
