# Generated by Django 5.0.6 on 2024-06-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printhub_app', '0009_remove_userfile_actual_page_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='actual_page_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
