# Generated by Django 5.0.6 on 2024-07-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printhub_app', '0010_userfile_actual_page_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
